### PR TITLE
Responsive design [Index-one.html]

### PR DESCRIPTION
**Pull request by falcon-head**
This is a test branch. 
Index-one.html contains the responsive design.
Did not check the backend.

*Made changes to front-end only*

### CODE REVIEW

**Review by cozyplanes — COMMENTED** [review]
1. Is this all needed? Seems too complicated for me.
2. Can you provide a live demo in your repository?

**Comment by cozyplanes** [comment]
@falcon-head Please review.

**Comment by falcon-head** [comment]
@cozyplanes can i do it after january 4th? Because i have sem exam till 4th.
*Had some free time other day! So tried to make changes* :)

**Comment by cozyplanes** [comment]
@falcon-head NP, btw, who r u in Gitter?

**Comment by falcon-head** [comment]
@cozyplanes i don't use gitter though! I use telegram :)

**Comment by Kimmax** [comment]
@cozyplanes please do not simply delete comments, just because you can. That's considered rude and doesn't really fit the open source world. Even if it wasn't relevant, let at least the collaborator decide..

**Comment by cozyplanes** [comment]
@Kimmax wait, i deleted comments? (not playing)

**Comment by Kimmax** [comment]
> cozyplanes deleted a comment from falcon-head a day ago

**Comment by cozyplanes** [comment]
Well, tbh, i don't remember me doing it. I remember messing up with some comments in one of the PRs here, and i guess this is. Sorry. But I am pretty sure it was redundant.

**Comment by falcon-head** [comment]
Hmm.. No clue what is happening here :joy: 
Just to be sure i will remove this pull request. Since it is not needed.

**Comment by cozyplanes** [comment]
So you won't work with this PR anymore?

**Comment by falcon-head** [comment]
I will work on it. At present just removing the pull request.

**Pull request closed without merging**
