### PR TITLE
Added forbidden character detection and username cookie storing

### PR DESCRIPTION
**Pull request by jonasgeiler**
Added the forbidden character detection (see #29) and a cookie that stores the username and automatically fills the input field on next page load. (Useful?)

### CODE REVIEW

**Comment by Kimmax** [comment]
Yes I think storing the username is useful, howeeeever we will need to add a cookie bar to comply with the EU Cookie Law

**Comment by Kimmax** [comment]
There are premade Plugins tho
Would you mind adding that to this PR? :)

**Comment by jonasgeiler** [comment]
You mean premade Plugins for some cookie popups?

**Comment by jonasgeiler** [comment]
Should I remove that feature again?
I think a cookie popup would kinda destroy the look of the site...

**Comment by Kimmax** [comment]
It doesn't need to be a popup, a small dismissable bar at the bottom is enough and only needs to be visible at the first vist
I kinda like the feature.. We'll probably use cookies one way or another anyways in the future

**Comment by jonasgeiler** [comment]
Okay there ya go!

**Comment by cozyplanes** [comment]
Some users may not like the autofill... Not me
So how about making a small not disruptive x button in the field?
@Skayo

**Review by cozyplanes — CHANGES_REQUESTED** [review]
Suggestion: A small x in the right side of the field

**Comment by Kimmax** [comment]
Autofill is there one way or another, let's keep it for starters and add an opt out option later on
An extra button seems more disruptive to me than autofill, we could just clear the field on focus

**Review by Kimmax — DISMISSED** [review]
I'd prefer clearing the input on focus over adding another button
You guys decide

**Comment by cozyplanes** [comment]
Nonono You mean when I typed the subtext wrong (like a spelling), touch somewhere else, and touches the input field again, it's gone? What a horrible experience. Add sth like this seems better FOR ME.

**Comment by jonasgeiler** [comment]
How about only show the x-Button if the script autofilled the field?
Otherwise never show it.

**Comment by cozyplanes** [comment]
Well showing the x button only when there is some text in the field may be better (i mean, you will put the button anyway...)

**Comment by Kimmax** [comment]
You were talking about how the AUTOFILL might not be wanted by users. So I responded to that. No context to invalid input at all.

> (i mean, **you will** put the button anyway...)

you have no right to force him to do anything. What you can do is to refuse a PR. That's it.
In my opinion you should practice to clearly communicate your wishes or you end up as the Project manager X that's getting ranted about.

**Comment by jonasgeiler** [comment]
There ya go!

**Review by Kimmax — APPROVED** [review]

**Review by cozyplanes — APPROVED** [review]

**Pull request merged**
