### PR TITLE
Redesign devBanner Frontend

### PR DESCRIPTION
**Pull request by LoganS1**
Here is the frontend I created yesterday. If you ever do credits my devRant username is @tisButABug, thanks! [Here](https://logans1.github.io/devBanner_Frontend/) is a link to a live site

### CODE REVIEW

**Comment by cozyplanes** [comment]
It doesnt seem to be working. We will check the APIs, but can you make sure the endpoints are correct? And the auto scaling doesnt work in chrome mobile, firefox mobile, and dolphin zero. Please check

**Comment by LoganS1** [comment]
It works fine on computer, however mobile doesn't seem to register the button click. I'll get right on it

**Comment by LoganS1** [comment]
Fixed the problem, I missed renaming a variable when cleaning up my code, now I'll take a look at the scaling issue on mobile

**Comment by cozyplanes** [comment]
@LoganS1

**Comment by LoganS1** [comment]
Scaling now works on mobile(tested on Chrome, Firefox, and Dophin Zero) along with the API calling!

**Review by cozyplanes — CHANGES_REQUESTED** [review]
1. Change `SubText:` label to `Subtext:`
2. Change the subtext placeholder to `Your subtext here`
3. Make both forms required by like this
`…autocomplete="false" required…`

This is a temporary fix until I make the changes to exception handling

**Comment by cozyplanes** [comment]
@LoganS1

**Comment by cozyplanes** [comment]
Can you also blur the bg as if like before?

**Comment by LoganS1** [comment]
I believe it is blurred? What browser are you using?
@cozyplanes

**Comment by LoganS1** [comment]
Maybe adding -webkit- will fix

**Comment by cozyplanes** [comment]
Seems ok for now, but i cqn fix the super small bugs as well as exceptions. Thanks!

**Comment by falcon-head** [comment]
Guys are we updating the template or should i create a new one?

**Comment by Kimmax** [comment]
Uhm @tahnik dud setup a webpack stack initially. Depends on what you would like to work on. If it's the real thing go for a fresh start using the stack you like (or use the webpack branch)
The current frontend is far from beautiful and still to be seen as temporary :)

**Comment by falcon-head** [comment]
Cool! Will update you on that.

**Comment by falcon-head** [comment]
Guys created a test branch called as responsive-design some shit. 
index-one.html contains the responsive page.
And i have created a pull request.

And i will be back after January 4th.

**Comment by Kimmax** [comment]
Will check later on, family for now

**Pull request merged**
